### ISSUE TITLE
When table is horizontally/vertically scrollable, header doesn't function correctly

### ISSUE THREAD

**Issue by MaestroJurko** [jmosbech/StickyTableHeaders#68]
![correct](https://cloud.githubusercontent.com/assets/616192/4250276/cba4ecf6-3a81-11e4-8885-4349bf56c402.png)
![notcorrect](https://cloud.githubusercontent.com/assets/616192/4250279/d00ed4b4-3a81-11e4-93fd-7df03ab6bdc9.png)

**Comment by cdfre** [comment]
<pre>newLeft = offset.left - scrollLeft + base.options.leftOffset;</pre>
In Line 139 is problematic for horizontal scrolling in a scrollable area

offset.left is the current offset of the element and therefore scrolling is already included in it.
<pre>newLeft = offset.left + base.options.leftOffset;</pre>
Works fine for scrollable areas (without the -scrollLeft)

**Comment by thatshowifeel** [comment]
@cdfre is right. I changed the code to match his and the headers align correctly in a scrollable area.

**Comment by TeodorKolev** [comment]
Does that issue resolved, or still not?

**Comment by ethanbeyer** [comment]
Has horizontal scrolling been fixed due to @simon04 's commit, or no?

**Comment by MartinGian** [comment]
What about this issue? This is fixed? I'm having the same problem with horizontal scroll bars. I tried the change of @simon04 but nothing changes.

**Comment by MartinGian** [comment]
@ethanbeyer Did you find a solution for this?

**Comment by ethanbeyer** [comment]
@MartinGian I did not, no...

**Comment by gabazureus** [comment]
Hey guys, I made some changes in the solution provided by **jpeck** in this link [https://github.com/jmosbech/StickyTableHeaders/issues/1](url) (and applied the fix said by **cdfre** here in this topic) and It worked here in my case.

Here is the new solution (stressed with data)
http://jsfiddle.net/2oeuvzLz/

I basically substituted the all the ".width()" to ".outerWidth()" and It worked fine

**Comment by zhanghuanchong** [comment]
@cdfre It's in line 157 in the latest version.

**Comment by maxlibin** [comment]
@gabazureus there is a resize problem, this should fix it

```
    base.updateWidth();
            base.toggleHeaders();
            base.$container.scroll(base.toggleHeaders);
            base.$container.resize(base.toggleHeaders);
            base.$container.resize(base.updateWidth);
            base.$window.scroll(function() {
                base.toggleHeaders();
                if(base.isCloneVisible) {
                    base.calcNewHeaderPosition();
                }
            });

            $(window).resize(function(){
                base.parentClientWidth = base.$container.outerWidth() - getScrollbarWidth();
                base.updateWidth()
            });
```

**Comment by simon04** [comment]
I might be worth looking for alternatives: https://mkoryak.github.io/floatThead/ 

> ` jquery.floatThead` is a floating/locked/sticky/fixed table header plugin that requires no special CSS and supports window and overflow scrolling. 

Its demo shows a table with vertical+horizontal scrollbars.

**Comment by amadeuszi** [comment]
My pull request #149 fixes the issue . Adding a clipping container fixes the isssue, and I fixed horizontal scrolling

**Comment by hamikm** [comment]
**Finally found a fix that works for me.**

My app contains a wide table in an `overflow-x: auto` container. Including only `$(#table_id).stickyTableHeaders();` floats the table header correctly as I scroll my whole document vertically, but it doesn't scroll the header when I scroll the table container horizontally.

I pulled #149 and used its `jquery.stickytableheaders.js`, but it didn't fix my problem. I also tried [simon04's alternative](https://mkoryak.github.io/floatThead/), but it didn't work either. Neither did the code snippets from bbearche and ghost in #122.

My solution was to just re-float the header when the table's container is scrolled horizontally. Worked like a charm. Not sure if this matters, but all style attributes on my table container and its children are in classes.

```
const $table = $('#table_id');
const $tableContainer = $('#table_container_id');
$table.stickyTableHeaders();
$tableContainer.scroll(function() {
    $table.stickyTableHeaders();
});
```
